version: '3.4'
volumes:
   volume:


services:
  
  book:
    image: ${DOCKER_REGISTRY-}book
    build:
      context: .
      dockerfile: Book/Dockerfile
    environment:
      DbServer: "mssql"
      DbPort: "1433"
      DbUser: "sa"
      Password: "Your_password123"
      Database: "books"
  data:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql
    environment:
      MSSQL_SA_PASSWORD: Your_password123
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
   
    volumes:
      - volume:/var/opt/mssql 
